### ISSUE TITLE
Issues using GetServiceStatus, GetMyFeesEstimate not implemented, and a patch.

### ISSUE THREAD

**Issue by risner** [interchange/Amazon-MWS#13]
I get a perl error using GetServiceStatus:
$res = $mws->GetServiceStatus();
Can't locate object method "GetServiceStatus" via package "Amazon::MWS::Client" at ./test-mws.pl line 136.

GetMyFeesEstimate isn't implemented, and looks complicated. It would be good to have, but I'm unable to code it at this time.

Sever subs had their version and service params swapped. I made them uniform. Simply a formatting correction.

Several needed a newer version, so I added version to them. I think at this point all Product require the newer version.

I've also implemented:
GetLowestPricedOffersForSKU
GetLowestPricedOffersForASIN
GetMyPriceForSKU
GetMyPriceForASIN

[Amazon-MWS-0.131-patch2.txt](https://github.com/interchange/Amazon-MWS/files/549635/Amazon-MWS-0.131-patch2.txt)

**Comment by racke** [comment]
Thanks a lot, I'll review your patch in the next few days.

**Comment by racke** [comment]
GetServiceStatus:fixed in 74b25c5.
