### ISSUE TITLE
Really need GetMyFeesEstimate working and I'm unable to code it myself

### ISSUE THREAD

**Issue by risner** [interchange/Amazon-MWS#14]
I tried below and the other attempt below again.

The first one just products a general exception and the second one says the PriceToEstimateFees option is empty.

define_api_method GetMyFeesEstimate =>
  raw_body => 0,
  service => $products_service,
  version => $version,
  parameters => {
                 MarketplaceId   => {
                                     type => 'string',
                                     required => 1
                                    },
                 IdType => {
                            type => 'string',
                            required => 1
                           },
                 IdValue => {
                            type => 'string',
                            required =>  1,
                           },
                 PriceToEstimateFees => {
                            type => 'List',
                            required =>  1,
                           },
                 Identifier => {
                            type => 'string',
                            required =>  1,
                           },
                 IsAmazonFulfilled => {
                           type => 'boolean',
                           required =>   1
                 },
              },
  respond => sub {
      my $root = shift;
      return unless $root; # failed totally
      if (ref($root) ne 'ARRAY') {
          return [ $root ];
      }
      else {
          return $root;
      }
  };

Also tried:
                 PriceToEstimateFees => {
                            array_names => ['ListingPrice'],
                            type => 'memberArray',
                            required =>  1,
                           },

**Comment by racke** [comment]
OK, I'll look at this as soon as possible.

**Comment by risner** [comment]
POST /Products/2011-10-01?AWSAccessKeyId=XXX
 &Action=GetMyFeesEstimate
 &SellerId=YYY
 &SignatureVersion=2
 &Timestamp=2016-11-05T21%3A04%3A29Z
 &Version=2011-10-01
 &Signature=ZZZ%3D
 &SignatureMethod=HmacSHA256
 &FeesEstimateRequestList.FeesEstimateRequest.1.MarketplaceId=ATVPDKIKX0DER
 &FeesEstimateRequestList.FeesEstimateRequest.1.IdType=ASIN
 &FeesEstimateRequestList.FeesEstimateRequest.1.IdValue=B00_Valid_one
 &FeesEstimateRequestList.FeesEstimateRequest.1.IsAmazonFulfilled=true
 &FeesEstimateRequestList.FeesEstimateRequest.1.Identifier=AAA_random_number
 &FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.Amount=9.49
 &FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.CurrencyCode=USD
 &FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.Shipping.Amount=0.00
 &FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.Shipping.CurrencyCode=USD

This worked (filling in the ASIN, username/password etc/ and such)

**Comment by risner** [comment]
Ok, got it working.
[fee.patch.txt](https://github.com/interchange/Amazon-MWS/files/573588/fee.patch.txt)

**Comment by risner** [comment]
test:
my @o = ( [ "ATVPDKIKX0DER", "ASIN", "B00XXXXX", "true", $t, "9.49", "USD", "0.00", "USD" ] );
my $res = $mws->GetMyFeesEstimate(
   FeesEstimateRequestList => \@o);

**Comment by racke** [comment]
Thanks for the patch - added it as 0349d95.
