### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [interchange/Amazon-MWS#7]
Your distribution (HORNBURG/Amazon-MWS-0.114.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=HORNBURG and contact me.

**Comment by racke** [comment]
Thanks chorny, I fixed the MANIFEST files so the MYMETA.* files are not part of the distribution any more - starting with the just released version 0.115.
